config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get "chats", to: "chatrooms#user_chatrooms"
  resources :pages, only: [:home, :show ]
  resources :places, only: :index
  resources :users, only: [:index, :update] do
     resources :user_interests, only: [:new, :create]
  end
  resources :friendships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places do
    resources :chatrooms do
      get "/add_participant/:id", to: 'chatrooms#add_participant', as: "add_participant"
      delete "/remove_participant/:id", to: 'chatrooms#remove_participant', as: "remove_participant"
      resource :chatroom_users
      resources :messages
    end
  end
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :chatroom_users
  has_many :users, through: :chatroom_users
  has_many :messages, dependent: :destroy
  belongs_to :place

  def available_nonparticipants
    User.all - users
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]

  # GET /chatrooms
  # GET /chatrooms.json
  def index
    @chatrooms = Chatroom.all
  end

  # GET /chatrooms/1
  # GET /chatrooms/1.json
  def show
    @messages = @chatroom.messages.order(created_at: :desc).limit(30).reverse
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new

  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms
  # POST /chatrooms.json
  def create
    # binding.pry
    place = Place.find(params[:place_id])
    place.chatrooms.each do |chatroom|
      if chatroom.users.include?(current_user)
        @chatroom = chatroom
        redirect_to place_chatroom_path(place, @chatroom)
        return
      end
    end

    @chatroom = place.chatrooms.create
    @chatroom.chatroom_users.create(user: current_user)
    redirect_to place_chatroom_path(place, @chatroom)

    # respond_to do |format|
    #   if @chatroom.save
    #     format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
    #     format.json { render :show, status: :created, location: @chatroom }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @chatroom.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /chatrooms/1
  # PATCH/PUT /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_participant
    @chatroom = Chatroom.find(params[:chatroom_id])
    @chatroom.chatroom_users.create(user_id: params[:id])
    redirect_to place_chatroom_path(@chatroom.place, @chatroom)
  end

  def remove_participant
    @chatroom = Chatroom.find(params[:chatroom_id])
    @chatroom.chatroom_users.where(user_id: params[:id]).first.destroy
    redirect_to place_chatroom_path(@chatroom.place, @chatroom)
  end

  def user_chatrooms
    @chatrooms = current_user.chatrooms
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def chatroom_params
    #   params.require(:chatroom).permit(:place_id)
    # end
end

app/views/chatrooms/_form.html.erb
<%= simple_form_for(@chatroom) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<div class="form-inputs">
  <%= f.input :name %>
</div>
<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>
chat = Chatroom.new(@place.name)

app/views/chatrooms/edit.html.erb
<h1>Editing Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Show', @chatroom %> |
<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/index.html.erb
<p id="notice"><%= notice %></p>
<h1>  Chatrooms</h1>
<div class="fluid-container">
  <div class="row">
    <div class="col-sm-2">
      <% if user_signed_in? %>
      <h5>Joined Chatrooms</h5>
      <ul>
        <% current_user.chatrooms.each do |chatroom| %>
        <li><%= link_to chatroom.name, chatroom %> </li>
        <% end %>
      </ul>
      <% end %>
      <!--  -->
      <table>
        <thead>
          <tr>
            <th>Chatroom List</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @chatrooms.each do |chatroom| %>
          <tr>
            <td><%= chatroom.name %> </td>
            <td><%= link_to 'Show', chatroom %></td>
            <td><%= link_to 'Edit', edit_chatroom_path(chatroom) %></td>
            <td><%= link_to 'Destroy', chatroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <td><%= link_to 'Join', chatroom_chatroom_users_path(chatroom), method: :post %></td>
            <td><%= link_to 'Leave', chatroom_chatroom_users_path(chatroom), method: :delete %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<br>
<%= link_to 'New Chatroom', new_chatroom_path %>

app/views/chatrooms/new.html.erb
<h1>New Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/show.html.erb
<div class="fluid-container col-sm-10 col-sm-offset-2" style="margin-bottom: 10px;">
  <p id="notice"><%= notice %></p>
  <%#= #link_to 'Edit', edit_chatroom_path(@chatroom) %>
  <div class="container"><h3><%= @chatroom.place.name %></h3></div>
</div>
<div style="margin-left: 10px; margin-right: 10px;">
  <nav >
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Chat</a>
      <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Friends in chat</a>
      <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Invite friends</a>
    </div>
  </nav>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" style="margin-top: 20px;" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
      <!-- #chat content -->
      <div data-behavior='messages'>
        <% @chatroom.messages.each do |message| %>
        <div class="<%= user_chat_class(message) %> pt-2 message-container" >
          <%= cl_image_tag message.user.photo, class: "avatar" %> <%= message.body %>
        </div>
        <% end %>
      </div>
      <%= simple_form_for [@chatroom.place, @chatroom, Message.new], remote:true do |f| %>
      <div class="input-group d-flex align-items-end message-composer">
        <%= f.text_area :body, rows: 1, placeholder: "Type a message", class: "form-control inputdefault", autofocus: false %>
        <div class="input-group-append ">
          <%= f.button :submit, 'send', class: "btn btn-outline-secondary border-10 " %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
      <div >
        <ul class="list-group" style="height: 250px; overflow: scroll;">
          <% @chatroom.users.each do |user| %>
          <div class="notification">
            <%= cl_image_tag(user.photo, class:'avatar-large') %>
            <div class="notification-content">
              <p><%= user.first_name %> <%= user.last_name %></p>
            </div>
            <div class="notification-actions">
              <%= link_to place_chatroom_remove_participant_path(@chatroom.place, @chatroom, user.id), method: :delete do%>
              <i class="fas fa-user-times"></i>
              <% end %>
            </div>
          </div>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
      <div >
        <ul class="list-group" style="height: 500px; overflow: scroll;">
          <% @chatroom.available_nonparticipants.each do |friend| %>
          <div class="notification">
            <%= cl_image_tag(friend.photo, class:'avatar-large') %>
            <div class="notification-content">
              <p><%= friend.first_name %> <%= friend.last_name %></p>
            </div>
            <div class="notification-actions">
              <%= link_to place_chatroom_add_participant_path(@chatroom.place, @chatroom, friend.id) do%>
              <i class="fas fa-user-plus"></i>
              <% end %>
            </div>
          </div>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/chatrooms/show_originale.html.erb
<div class="fluid-container col-sm-10 col-sm-offset-2" style="margin-bottom: 10px;">
  <p id="notice"><%= notice %></p>
  <%#= #link_to 'Edit', edit_chatroom_path(@chatroom) %>
<div class="container"><h3><%= @chatroom.place.name %></h3></div>
</div>

<div style="margin-left: 10px; margin-right: 10px;">
  <nav >
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Chat</a>
      <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Friends in chat</a>
      <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Invite friends</a>
    </div>
  </nav>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" style="margin-top: 20px;" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
      <!-- #chat content -->
      <div>
        <div data-behavior='messages'>
          <% @chatroom.messages.each do |message| %>

          <div><%= cl_image_tag message.user.photo, class: "avatar" %><strong> <%= message.user.username_initial%>: </strong>  <%= message.body %></div>
          <% end %>
        </div>
        <%= simple_form_for [@chatroom.place, @chatroom, Message.new], remote:true do |f| %>

        <div class="input-group d-flex align-items-end">
        <%= f.text_area :body, rows: 1, placeholder: "Type a message", class: "form-control inputdefault", autofocus: false %>
          <div class="input-group-append ">
        <%= f.button :submit, 'send', class: "btn btn-outline-secondary border-10 " %>
        <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
      <div >
        <ul class="list-group" style="height: 250px; overflow: scroll;">
         <% @chatroom.users.each do |user| %>
         <li class="list-group-item d-flex justify-content-between align-items-center"> <%= user.first_name %> <%= user.last_name %>
          <span class="badge badge-friendzy badge-pill"> <%= link_to "Remove", place_chatroom_remove_participant_path(@chatroom.place, @chatroom, user.id), method: :delete %> </span>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
    <div >
      <ul class="list-group" style="height: 500px; overflow: scroll;">
       <% @chatroom.available_nonparticipants.each do |friend| %>
       <li class="list-group-item d-flex justify-content-between align-items-center"> <%= friend.first_name %> <%= friend.last_name %>
        <span class="badge badge-friendzy badge-pill"><%= link_to "Add", place_chatroom_add_participant_path(@chatroom.place, @chatroom, friend.id) %> </span>
      </li>
      <% end %>
    </ul>
  </div>

  </div>
</div>
</div>

app/views/chatrooms/user_chatrooms.html.erb
<div >
<ul class="list-group ">
<li class="list-group-item align-items-left list-group-item-primary text-white"> <strong> Chats</strong></li>

<% @chatrooms.each do |chatroom| %>

  <li class="list-group-item justify-content-start list-group-item-light "><%= link_to place_chatroom_path(chatroom.place, chatroom) do %>
  <p class="text-secondary"> 💬 <%= chatroom.place.name %></p>
  <% end %>
  </li>
<% end %>
</div>