config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get "chats", to: "chatrooms#user_chatrooms"
  resources :pages, only: [:home, :show ]
  resources :places, only: :index
  resources :users, only: [:index, :update] do
     resources :user_interests, only: [:new, :create]
  end
  resources :friendships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places do
    resources :chatrooms do
      get "/add_participant/:id", to: 'chatrooms#add_participant', as: "add_participant"
      delete "/remove_participant/:id", to: 'chatrooms#remove_participant', as: "remove_participant"
      resource :chatroom_users
      resources :messages
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<% if current_user %>


<div class="footer-container">
  <div class="mobile-bottom-bar">

    <a href="#" class="footer-link">
     <%= link_to page_path(current_user) do %>
      <i class="fas fa-user" style="color: white"></i> <span class='footer-text' style="color: white"></span>
      <% end %>
    </a>

    <a href="#" class="footer-link">
      <%= link_to users_path do %>
      <i class="fas fa-users" style="color: white"></i> <span class='footer-text' style="color: white"></span>
      <% end %>
    </a>

    <a href="#" class="footer-link">
      <%= link_to places_path do %>
      <i class="fas fa-map-marker-alt"style="color: white"></i> <span class='footer-text' style="color: white"></span>
      <% end %>
    </a>

    <a href="#" class="footer-link">
     <%= link_to  chats_path do%>
      <i class="fas fa-comment" style="color: white"></i> <span class='footer-text' style="color: white"></span>
      <% end %>
    </a>
  </div>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo-friendzy.png" %>
    <%#= image_tag('home-logo2.png', alt: 'Home avatar') %>
    <% end %>

   <!--  <a class="navbar-friendzy">

      <%#= image_tag('Friendzy-logo4.png', size: '180x60', alt: 'Friendzy Logo') %>

    </a> -->

  <div>
    <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <% if current_user.photo.file.nil? %>
          <%= image_tag "Profile-logo1.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Profile", page_path(current_user), class: "dropdown-item" %>
          <%= link_to "Settings", "#", class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    <% else %>
      <li class="nav-item dropdown">
        <%= image_tag "Profile-logo1.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </div>
      </li>
    <% end %>
  </div>
</div>