config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get "chats", to: "chatrooms#user_chatrooms"
  resources :pages, only: [:home, :show ]
  resources :places, only: :index
  resources :users, only: [:index, :update] do
     resources :user_interests, only: [:new, :create]
  end
  resources :friendships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places do
    resources :chatrooms do
      get "/add_participant/:id", to: 'chatrooms#add_participant', as: "add_participant"
      delete "/remove_participant/:id", to: 'chatrooms#remove_participant', as: "remove_participant"
      resource :chatroom_users
      resources :messages
    end
  end
end

app/views/pages/home.html.erb
<div class="banner" style='background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "landing-photo1.jpg" %>);'>
  <div class="container">
    <h1><strong>Friendzy</strong><h1>
    <p>Keep in touch with your closest friends</p>
  </div>
  <div>
    <%= link_to "Meet Friends", places_path, :class => "btn btn-friendzy text-center btn-padding-interest text-white"  %>
  </div>
</div>

app/views/pages/show.html.erb
<div class="text-center">
  <p><%= cl_image_tag((@friend.photo), class: "profile_photo") %></p>
  <p><strong><%=@friend.first_name.upcase %> <%= @friend.last_name.upcase  %></strong></p>
</div>

<!-- OLD CODE FOR SHOWING INTERESTS -->
<%# if @friend.interests.any? %>
<!-- <div class="text-center">
  <em> Interested in: </em>
  <%# @friend.interests.each do |int| %>
  <ul class="hello">
    <li class="bg-light"><%#= int.name %></li>
  </ul>
  <%# end %>
  <%# else %>
  <%# if @user == @friend %>
  <em>You don't have interests yet.</em>
  <div >
    <%#= link_to "Add an interest",new_user_user_interest_path(current_user), :class => "btn btn-outline-primary"  %>
  </div>
  <%# else %>
  <div class="bg-light p-5">
    <%= @friend.first_name %><%#= " doesn't have any interest yet." %>
  </div>
  <%# end %>
  <%# end %>
</div>
-->
<!-- OLD CODE FOR SHOWING INTERESTS -->
<!-- new CODE FOR SHOWING INTERESTS -->
<% if @user == @friend %>
<% if @friend.interests.any? %>
<% @friend.interests.each do |int| %>
<ul class="hello">
  <li class="bg-light"><%= int.name %></li>
</ul>
<% end %>
<div >
  <%= link_to "Add an interest",new_user_user_interest_path(current_user), :class => "btn btn-friendzy text-center btn-padding-interest text-white"  %>
</div>
<% else %>
<em>You don't have interests yet.</em>
<div >
  <%= link_to "Add an interest",new_user_user_interest_path(current_user), :class => "btn btn-outline-primary"  %>
</div>
<% end %>
<% else %>
<% if @friend.interests.any? %>
<% @friend.interests.each do |int| %>
<ul class="hello">
  <li class="bg-light"><%= int.name %></li>
</ul>
<% end %>
<% else %>
<em><%= @friend.first_name %><%= " doesn't have any interest yet." %></em>
<% end %>
<% end %>
<!-- new CODE FOR SHOWING INTERESTS -->
<% if @friend_av.any? %>
<div class="bg-light">
  <p> <%= week_calendar events: @friend_av do |date, avs| %>
    <%= date %>
    <% avs.each do |av| %>
    <div class="text-center">
      <%= "☑" %>
    </div>
    <% end %>
    <% end %>
  </p>
</div>
<% else %>
<div class="bg-light p-5">
  <%= @friend.first_name %> has not specified availabilities yet.
</div>
<% end %>
<div>
  <%= simple_form_for(@friend, html: { method: :put }) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs ">
    <%= f.input :photo %>
  </div>
  <div class="form-actions btn-friendzy text-center btn-padding-update ">
    <%= f.button :submit, "Save Profile", class: "text-white"%>

  </div>
  <% end %>
</div>