config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get "chats", to: "chatrooms#user_chatrooms"
  resources :pages, only: [:home, :show ]
  resources :places, only: :index
  resources :users, only: [:index, :update] do
     resources :user_interests, only: [:new, :create]
  end
  resources :friendships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places do
    resources :chatrooms do
      get "/add_participant/:id", to: 'chatrooms#add_participant', as: "add_participant"
      delete "/remove_participant/:id", to: 'chatrooms#remove_participant', as: "remove_participant"
      resource :chatroom_users
      resources :messages
    end
  end
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :place_categories
  has_many :interests, through: :place_categories
  has_many :chatrooms

  validates :name, presence: true
  validates :category, presence: true
  validates :address, presence: true
  mount_uploader :photo, PhotoUploader

  include PgSearch
  pg_search_scope :search_by_name_and_category_and_address,
                  against: %i[name category address],
                  using: { tsearch: { prefix: true } }
end

app/controllers/places_controller.rb
require_relative "../services/foursquare_api.rb"

class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    if params[:query].present?
      search_api("Milan",params[:query])

      sql_query = "name ILIKE :query OR category ILIKE :query OR address ILIKE :query"
      @places = Place.where(sql_query, query: "%#{params[:query]}%")
    else
      @places = Place.all
    end
  end

  def show
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to @place
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @place.update(place_params)
      redirect_to @place
    else
      render :edit
    end
  end

  private

  def set_place
    @place = Place.find(params[:id])
  end

  def place_params
    params.require(:place).permit(:name, :category, :address, :rating, :photo)
  end
end

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= form_for @place do |f| %>
  <%= f.text_field :name %><br />

  <%= f.label :category %>:
  <%= f.text_field :category %><br />

  <%= f.label :address %>:
  <%= f.text_field :address %><br />

  <%= f.label :rating %>:
  <%= f.text_field :rating %><br />

  <%= f.submit %>
<% end %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<%= form_tag places_path, method: :get, class: "search-form" do %>
<%= text_field_tag :query,
params[:query],
class: "form-control search-form-flexgrow",
placeholder: "Find a place to hang out" %>
<%= button_tag(type: "submit", class: "btn btn-friendzy-search mr-4") do %>
<i class="fas fa-search"></i>
<% end %>
<% end %>
<div class="container-places">
  <div class="row d-flex justify-content-center align-bottom">
    <% @places.each do |place| %>
    <div>
      <%= link_to place_path(place) do %>
      <div class="card text-white">
        <%= cl_image_tag(place.photo, height: 200, width: 80, class: 'card-img')%>
        <div class="card-img-overlay d-flex flex-column justify-content-end">
          <h5 class="card-title font-weight-bold mb-0"><%= place.name %></h5>
          <p class="card-text font-weight-lighter"> <%= place.address %></p>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>
    </div>   <!-- container-places end -->
  </div>

app/views/places/new.html.erb
<%= form_for @place do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.label :category %>:
  <%= f.text_field :category %><br />

  <%= f.label :address %>:
  <%= f.text_field :address %><br />

  <%= f.label :rating %>:
  <%= f.text_field :rating %><br />

  <%= f.submit %>
  <% end %>

app/views/places/show.html.erb
<!-- <div class="card-show-places-container ">
  <div class="card-show-places">
    <div class="card-show-places-infos">
      <div>
        <%= cl_image_tag(@place.photo) %>
        <h2><%#= @place.name %></h2>
        <p><%= @place.address %></p>
        <p>Category: <%= @place.category %></p>
      </div>
    </div>
  </div>  <#!--card-show-places  end -->
  <!-- </div>   --> <!-- card-show-places-container  end-->
  <%#= link_to "Invite Friends", place_chatrooms_path(@place), method: :post %>
  <div class="card" pt-0>
    <%= cl_image_tag(@place.photo, transformation: [
    {:width=>400, :height=>250, :gravity=>"south", :crop=>"fill"}]) %>
    <div class="card-img-overlay">
      <h5 class="card-title text-white"> <strong> <%= link_to "<", places_path, {:style=>'color:#FFFFFF;'} %></strong> </h5>
    </div>
    <!-- <div class="card-body mx-5"> -->
    <!-- <div class="card-place"> -->
    <div class=" card-place row d-flex justify-content-center align-bottom">
      <div class="card-place-infos">
        <h5 class="card-title"><%= @place.name %></h5>
        <p class="card-text"><%= @place.description %></p>
        <div class="text-center card-button-pos">
          <div class="btn btn-friendzy btn-padding-show">
            <%= link_to "Go here!", place_chatrooms_path(@place), method: :post, class: 'text-white font-weight-bold'  %>
          </div>
        </div>
      </div>
      </div>  <!-- class card place-->
      </div>  <!-- class card end-->